### ISSUE TITLE
バージョン29以上での動作状況

### ISSUE THREAD

**Issue by ujimushi** [kanchoku/tc#17]
`tc.el`が利用しているEmacs本体の関数の名前が`24.3`から変更されていて, バージョンの28.xまではobsoleteのエイリアスだったのですが, 29.0の途中からばっさり削除されています。

この影響が`tc.el`にも及んでうまく動かないようです。
`tc.el`不動作不具合につながるものは私が把握している限り次の通りです。

* `input-method-inactivate-hook` → `input-method-deactivate-hook`
* `inactivate-current-input-method-function` → `deactivate-current-input-method-function`
* `set-face-underline-p` → `set-face-underline`

上記以外の`deactivate-input-method`等は，既に対策済みと思われます。

パッケージ修正前の暫定の対策として，`init.el`の早い段階で
```elisp
(defvaralias 'input-method-inactivate-hook 'input-method-deactivate-hook)
(defvaralias 'inactivate-current-input-method-function 'deactivate-current-input-method-function)
(defalias 'set-face-underline-p 'set-face-underline)
```
とすることで不具合を回避できると思われます。

なお，こちらで確認している動作不具合の現象としては
* 漢直入力モードから直接入力モードに復帰できない。`toggle-input-method`が効かない。
* 交ぜ書き変換をしようとするとエラーが発生する

です。

修正方法案についてですが，機械的に前述の関数名を置き換えるのが一番簡単かな?と思います。

ただ，この場合24.3(2013年3月リリース)より前のバージョンのサポートを切る感じになります。
もっとも，CIによるバイトコンパイルの確認も24.5で行っているので現状でサポートできているか
どうかも微妙な感じです。

**Comment by naota** [comment]
詳細レポ一トありがとうございます。一応わたしも把握していて、以下のpatchで運用しています。
置き換えになりますね。

```
diff --git a/tc-mazegaki.el b/tc-mazegaki.el
index d2e5f1280c3c..cedef3ddc8e3 100644
--- a/tc-mazegaki.el
+++ b/tc-mazegaki.el
@@ -91,7 +91,7 @@ nil の場合には保存されない。")
       nil
     (prog1
 	(make-face 'mazegaki-conversion)
-      (set-face-underline-p 'mazegaki-conversion t)))
+      (set-face-underline 'mazegaki-conversion t)))
   "* 交ぜ書き変換の変換対象を表す文字列に用いるface。
 mule2 以上または XEmacs の場合のみ有効。")
 (defvar tcode-mazegaki-prefix-overlay nil)
diff --git a/tc.el b/tc.el
index 4bf4395f1bca..1b49fe120426 100644
--- a/tc.el
+++ b/tc.el
@@ -1155,6 +1155,7 @@ Tコードモードについては、\\[tcode-mode-help] で表示されるヘ
       ;; バッファごとのTコードの初期化を行う。`tcode-mode-hook'を呼ぶ。
       (setq tcode-ready-in-this-buffer t)
       (run-hooks 'tcode-mode-hook))
+    (setq deactivate-current-input-method-function 'tcode-inactivate)
     (run-hooks 'input-method-activate-hook)
     (when tcode-use-input-method
       (set (make-local-variable 'input-method-function)
```

emacsのpackageは習慣的にはaliasで互換性を保つようにがんばることが多いように思うのですが、メンテの大変さと人手を考えると、サポートを切る方向で行きたいと思います。

**Comment by ujimushi** [comment]
> サポートを切る方向で行きたいと思います

了解です。24.3からでももう10年以上経ちますし，プリコンパイル時のobosoleteメッセージも気になるところでした。

29.0.xxのプレビュー版の途中から動かないことが分かっていたのですが放置していて，ubuntuの最新版が29.1になっているので次のLTS版までには対策しようかということで，詳しく調べてみた感じです。

Emacs本体のこの関数名の変更は，元々`inactivate...`はmule(日本の開発者?)由来のコードで，emacs本体に組み込まれてかなり経って，英語圏では`deactivate...`の方が一般的だから…とかいう感じだったような想像をしています。

ぐぐってみると，英語に`inactivate`という単語はない，ということのようです(`inactive`はある)。
<https://ja.hinative.com/questions/1555504>
