### ISSUE TITLE
Emacs 25.1におけるobsolete variableの存在

### ISSUE THREAD

**Issue by Tacumi** [kanchoku/tc#3]
起動時に"Warning (bytecomp): ‘isearch-word’ is an obsolete variable (as of 25.1); use ‘isearch-regexp-function’ instead."とメッセージが出力されるため，isearch-wordを置き換えた方が良いのではないか．

**Comment by deton** [comment]
参考: migemo.elの対応。
https://github.com/emacs-jp/migemo/pull/22/files

**Comment by ujimushi** [comment]
deton さんのコメントを参考に修正方法を検討しています。
#4 の対応( #6 )をマージすると，Emacs 23～26でのbyteコンパイルの自動テストの結果が
確認できるようになるので，それが終わってから対応します。
過去にしょぼい対応 ( https://srad.jp/~ujimushi/journal/588062/ ) をしているので
そこも改善してファイルをーつにまとめようと思います。
